global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'nexus-api'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'nexus-pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']